perf tools: Fix compile error for x86
Commit a0a12c3ed057 ("asm goto: eradicate CC_HAS_ASM_GOTO") removes
CC_HAS_ASM_GOTO, perf on x86 call asm_volatile_goto when compiling __GEN_RMWcc.

However, asm_volatile_goto is not declared, which causes compilation error:

	In file included from /home/linux/tools/include/asm/../../arch/x86/include/asm/atomic.h:7,
			 from /home/linux/tools/include/asm/atomic.h:6,
			 from /home/linux/tools/include/linux/atomic.h:5,
			 from /home/linux/tools/include/linux/refcount.h:41,
			 from /home/linux/tools/lib/perf/include/internal/cpumap.h:5,
			 from /home/linux/tools/perf/util/cpumap.h:7,
			 from /home/linux/tools/perf/util/env.h:7,
			 from /home/linux/tools/perf/util/header.h:12,
			 from pmu-events/pmu-events.c:9:
	/home/linux/tools/include/asm/../../arch/x86/include/asm/atomic.h: In function ‘atomic_dec_and_test’:
	/home/linux/tools/include/asm/../../arch/x86/include/asm/rmwcc.h:7:2: error: implicit declaration of function ‘asm_volatile_goto’ [-Werror=implicit-function-declaration]
	  asm_volatile_goto (fullop "; j" cc " %l[cc_label]"  \
	  ^~~~~~~~~~~~~~~~~

Solution:
Define asm_volatile_goto in compiler_types.h if not declared.

Currently, only x86 architecture uses asm_volatile_goto.
Theoretically, this patch affects only the x86 architecture.

Fixes: a0a12c3ed057 ("asm goto: eradicate CC_HAS_ASM_GOTO")
Signed-off-by: Yang Jihong <yangjihong1@huawei.com>
Signed-off-by: Ingo Molnar <mingo@kernel.org>
Link: https://lore.kernel.org/r/20220822092557.210209-1-yangjihong1@huawei.com